// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-eHQaRsHuGsjgl4AfIJR_g2GpgJAfYJI',
    appId: '1:1027595122366:web:10a9060e85eef9f99210ef',
    messagingSenderId: '1027595122366',
    projectId: 'whatsappweb-81cc8',
    authDomain: 'whatsappweb-81cc8.firebaseapp.com',
    storageBucket: 'whatsappweb-81cc8.firebasestorage.app',
    measurementId: 'G-HJK51Q7VS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDT9PqIDHNMDIG2bVmq_flNHw51JYQWuA',
    appId: '1:1027595122366:android:8bb56be992d296d29210ef',
    messagingSenderId: '1027595122366',
    projectId: 'whatsappweb-81cc8',
    storageBucket: 'whatsappweb-81cc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjK0luqZqT1dP64jC_QOENwaFMpaGQls',
    appId: '1:1027595122366:ios:c3579708ce282f629210ef',
    messagingSenderId: '1027595122366',
    projectId: 'whatsappweb-81cc8',
    storageBucket: 'whatsappweb-81cc8.firebasestorage.app',
    iosBundleId: 'com.example.whatsappWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAjK0luqZqT1dP64jC_QOENwaFMpaGQls',
    appId: '1:1027595122366:ios:c3579708ce282f629210ef',
    messagingSenderId: '1027595122366',
    projectId: 'whatsappweb-81cc8',
    storageBucket: 'whatsappweb-81cc8.firebasestorage.app',
    iosBundleId: 'com.example.whatsappWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-eHQaRsHuGsjgl4AfIJR_g2GpgJAfYJI',
    appId: '1:1027595122366:web:ac536e5236ddef419210ef',
    messagingSenderId: '1027595122366',
    projectId: 'whatsappweb-81cc8',
    authDomain: 'whatsappweb-81cc8.firebaseapp.com',
    storageBucket: 'whatsappweb-81cc8.firebasestorage.app',
    measurementId: 'G-QK6BGVP0SD',
  );
}
